### ISSUE TITLE
unable to install eclim

### ISSUE THREAD

**Issue by TimEichholz** [ervandew/eclim#552] opened 2018-01-09 17:14 UTC
I'm unable to install eclim with a fresh Eclipse installation and the new command line installer.
Is there anyway to fix it?

[1515517256520.log](https://github.com/ervandew/eclim/files/1615963/1515517256520.log)
!SESSION 2018-01-09 18:00:56.356 -----------------------------------------------
eclipse.buildId=4.7.2.M20171130-0510
java.version=9.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_DE
Framework arguments:  -application org.eclipse.equinox.p2.director -uninstallIU org.eclim.feature.group
Command-line arguments:  -application org.eclipse.equinox.p2.director -uninstallIU org.eclim.feature.group

!ENTRY org.eclipse.equinox.p2.director.app 4 0 2018-01-09 18:00:59.173
!MESSAGE The installable unit org.eclim.feature.group has not been found.

**Comment by ervandew** [comment] 2018-01-09 17:27
> with a fresh Eclipse installation

Did you attempt to install eclim some other way before you got to the error you posted?
Was you fresh eclipse installation peformed over top of an existing install?

It looks like the installer sees the org.eclim.feature in your eclipse install, but the eclipse p2 director doesn't. You may need to manually remove all org.eclim* dirs from your eclipse `features` and `plugins` directories.  You can run the command line installer with the `--debug` option to see which feature paths the installer is looking at.

**Comment by TimEichholz** [comment] 2018-01-09 19:16
thanks for the fast reply, I had missed out deleting the .p2 directory in my home directory. After deleting it the eclim installer worked. But trying to execute the now installed eclim throws an error:

Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/eclipse/ui/PlatformUI
	at org.eclim.eclipse.EclimApplication.shutdown(EclimApplication.java:144)
	at org.eclim.eclipse.EclimApplication$1.run(EclimApplication.java:102)
Caused by: java.lang.ClassNotFoundException: org.eclipse.ui.PlatformUI cannot be found by org.eclim_2.7.1
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 2 more

[log.log](https://github.com/ervandew/eclim/files/1616306/log.log)

**Comment by ervandew** [comment] 2018-01-09 21:02
> java.lang.NoClassDefFoundError: org/eclipse/ui/PlatformUI

I've never ran across that, but to me that looks like eclipse is a bit fubar. I'd recommend removing the existing eclipse install completely (including the ~/.p2 dir) and re-installing eclipse.

**Comment by TimEichholz** [comment] 2018-01-09 23:38
I completely deleted eclipse with the .p2 and .eclipse dir in my home directory as well some other directories that I found with mdfind and locate + some software, still throwing java.lang.NoClassDefFoundError. Ill do some more trial and error the next days.
The log file looks like this:

!SESSION 2018-01-10 00:08:36.840 -----------------------------------------------
eclipse.buildId=4.7.2.M20171130-0510
java.version=9.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.core.net 1 0 2018-01-10 00:09:59.094
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences
!SESSION 2018-01-10 00:26:56.862 -----------------------------------------------
eclipse.buildId=4.7.2.M20171130-0510
java.version=9.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_DE
Framework arguments:  --launcher.suppressErrors -refresh -application org.eclim.application
Command-line arguments:  --launcher.suppressErrors -debug -clean -refresh -application org.eclim.application

!ENTRY org.eclipse.osgi 4 0 2018-01-10 00:27:04.968
!MESSAGE Application error
!STACK 1
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:410)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:491)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:505)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:204)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:614)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclim.eclipse.EclimApplication.start(EclimApplication.java:128)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
	... 24 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 26 more

!ENTRY org.eclipse.e4.ui.workbench 4 0 2018-01-10 00:27:04.982
!MESSAGE FrameworkEvent ERROR
!STACK 0
java.lang.NoClassDefFoundError: javax/annotation/PreDestroy
	at org.eclipse.e4.core.internal.di.InjectorImpl.disposed(InjectorImpl.java:450)
	at org.eclipse.e4.core.internal.di.Requestor.disposed(Requestor.java:156)
	at org.eclipse.e4.core.internal.contexts.ContextObjectSupplier$ContextInjectionListener.update(ContextObjectSupplier.java:78)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:111)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.handleInvalid(TrackableComputationExt.java:74)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:178)
	at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.dispose(EclipseContextOSGi.java:99)
	at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.bundleChanged(EclipseContextOSGi.java:141)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:476)
	at org.eclipse.osgi.container.Module.doStop(Module.java:634)
	at org.eclipse.osgi.container.Module.stop(Module.java:498)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:202)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:165)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: javax.annotation.PreDestroy cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 21 more

**Comment by ervandew** [comment] 2018-01-10 00:06
Very weird. Now that it's not finding a javax class, i'm a worried that this has gone beyond eclipse. What other directories did you delete?

**Comment by TimEichholz** [comment] 2018-01-10 15:49
Fixed the error by adding `export JAVA_HOME="/usr/libexec/java_home -v 1.8"` to my shells init file. Eclim with java 9 don't seems to work for me. Thanks for the fast help.

**Comment by ervandew** [comment] 2018-01-10 16:31
It looks like the eclipse guys battled with supporting Java 8 and 9 concurrently:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=493761

When I get a chance I'll install java 9 and see what I can come up with. The eclimd script may just have a bug when it contructs the eclipse launcher args using eclipse.ini

**Comment by ervandew** [comment] 2018-01-10 16:33
I'm going to close this issue since the original problem was addressed. If you want to create a new issue to track running eclimd with Java 9, feel free (I'll work on a fix either way when I get the time).

**Closed by ervandew** 2018-01-10 16:33 UTC

**Comment by ervandew** [comment] 2018-01-10 17:24
@TimEichholz 
If you get a chance, you can try out the latest version of the eclimd script (this should fix starting eclimd with java 9)?
https://raw.githubusercontent.com/ervandew/eclim/master/org.eclim/bin/eclimd

Backup your existing eclimd script first, just in case. Also be sure to replace eclimd found in `plugins/org.eclim_<version>/bin/` instead of the symlink the installer creates.

**Comment by TimEichholz** [comment] 2018-01-10 18:35
Tried out the new eclimd script. Starting it throws an IllegalStateException.

LOG:
!SESSION 2018-01-10 19:29:52.969 -----------------------------------------------
eclipse.buildId=unknown
java.version=9.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_DE
Framework arguments:  --launcher.suppressErrors -refresh -application org.eclim.application
Command-line arguments:  --launcher.suppressErrors -debug -clean -refresh -application org.eclim.application

!ENTRY org.eclipse.osgi 4 0 2018-01-10 19:29:54.079
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:78)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

**Comment by ervandew** [comment] 2018-01-10 18:43
Can you post the output from eclimd? I want to at least make sure that is running correctly.

Also, can you start the eclipse gui or do you get the same error?

**Comment by TimEichholz** [comment] 2018-01-10 19:16
Eclipse gui works fine. The output of eclimd with --debug is the following:

/usr/bin/java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
JAVA_VERSION=9

/usr/bin/java -d64 -Xmx256m -XstartOnFirstThread -Dorg.eclim.debug -jar /Users/tim/.p2/pool/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar --launcher.suppressErrors -debug -clean -refresh -application org.eclim.application
Install location:
    file:/Users/tim/.p2/pool/
Configuration file:
    file:/Users/tim/.p2/pool/configuration/config.ini not found or not read
Configuration location:
    file:/Users/tim/.p2/pool/configuration/
Configuration file:
    file:/Users/tim/.p2/pool/configuration/config.ini not found or not read
Framework located:
    file:/Users/tim/.p2/pool/plugins/org.eclipse.osgi_3.12.50.v20170928-1321.jar
Framework classpath:
    file:/Users/tim/.p2/pool/plugins/org.eclipse.osgi_3.12.50.v20170928-1321.jar
Debug options:
    file:/Users/tim/.options not found
Time to load bundles: 2
An error has occurred. See the log file
/Users/tim/.p2/pool/configuration/1515611656472.log.

**Comment by ervandew** [comment] 2018-01-10 20:49
Cool, at least it looks like my eclimd changes are working correctly.  As for the error, it may be osx related since I can't reproduce it on my linux box.

**Comment by vlurgio** [comment] 2018-06-15 14:11
Yeah if you've tried in the past theres a couple things in ~/Library that the installer caches thatll confuse the installer even if you have done rm -rf eclipse
